ghost:
  enabled: true
  replicas: 1

  image:
    tag: 5.89.0

  deployment:
    create: true

  container:
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    env:
      - name: NODE_ENV
        value: production
      - name: url
        value: https://diary.nabi.kim
      - name: database__client
        value: mysql
      - name: database__connection__host
        value: personal-note-database
      - name: database__connection__database
        valueFrom:
          secretKeyRef:
            name: note-database-secret
            key: database
      - name: database__connection__user
        valueFrom:
          secretKeyRef:
            name: note-database-secret
            key: username
      - name: database__connection__password
        valueFrom:
          secretKeyRef:
            name: note-database-secret
            key: password
      - name: mail__from
        value: note@nabi.kim

  volumes:
    - name: note-ghost-contents
      persistentVolumeClaim:
        claimName: note-ghost-contents

  volumeMounts:
    - name: note-ghost-contents
      mountPath: /var/lib/ghost/content

  service:
    create: true

  ingress:
    create: true
    className: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    hosts:
      - host: diary.nabi.kim
        paths:
          - path: /
            pathType: Prefix
            svcPort:
              name: ghost
    tls:
      - secretName: ghost-tls
        hosts:
          - blog.k8s.nabi.kim

  storageClass:
    create: true
    provisioner: kubernetes.io/no-provisioner
    volumeBindingMode: WaitForFirstConsumer

  persistentVolumes:
    - name: note-ghost-contents
      accessModes:
        - ReadWriteMany
      size: 20Gi
      path: /k3s-volumes/note/ghost-content
      reclaimPolicy: Retain
      claim:
        create: true

mariadb:
  enabled: true
  replicas: 1

  deployment:
    create: true

  container:
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: note-database-secret
            key: root-password
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: note-database-secret
            key: username
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: note-database-secret
            key: password
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: note-database-secret
            key: database

  volumes:
    - name: note-database
      persistentVolumeClaim:
        claimName: note-database

  volumeMounts:
    - name: note-database
      mountPath: /var/lib/mysql

  service:
    create: true

  storageClass:
    create: true
    provisioner: kubernetes.io/no-provisioner
    volumeBindingMode: WaitForFirstConsumer

  persistentVolumes:
    - name: note-database
      accessModes:
        - ReadWriteMany
      size: 5Gi
      path: /k3s-volumes/note/database
      reclaimPolicy: Retain
      claim:
        create: true
