{{ if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "gh-eventsource.fullname" . }}
  namespace: {{ include "gh-eventsource.namespace" . }}
  labels: {{- include "gh-eventsource.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    name: {{ required "issuer name is required!" .Values.certificate.issuerRef.name }}
    kind: {{ default "ClusterIssuer" .Values.certificate.issuerRef.kind }}
  dnsNames: {{ toYaml .Values.certificate.dnsNames | nindent 4 }}
{{- end -}}
