apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ include "gh-eventsource.fullname" . }}
  namespace: {{ include "gh-eventsource.namespace" . }}
  labels: {{- include "gh-eventsource.labels" . | nindent 4 }}
spec:
  service:
    ports:
      - name: {{ include "gh-eventsource.fullname" . }}
        port: {{ default 12000 .Values.service.port }}
        targetPort: {{ default 12000 .Values.service.port }}
    github:
      webhook:
        repositories: {{ if .Values.github.repositories -}}
            {{- range $i, $repository := .Values.github.repositories }}
          - owner: {{ $repository.owner }}
            names:
              {{- range $j, $name := $repository.names }}
              - {{ $name }}
              {{- end -}}
            {{ end -}}
          {{- else -}}
             []
          {{- end }}
        webhook:
          endpoint: {{ .Values.webhook.endpoint }}
          port: {{ .Values.webhook.port }}
          method: "POST"
          url: {{ .Values.webhook.url }}
        events:
          {{ if .Values.webhook.events -}}
            {{- range $index, $event := .Values.webhook.events -}}
            - {{ $event }}
            {{- end -}}  
          {{ else -}}
            - "*"
          {{- end }}
        apiToken:
          name: {{ .Values.webhook.apiToken.name }}
          key: {{ .Values.webhook.apiToken.key | b64enc | quote }}
        insecure: {{ default true .Values.webhook.insecure }}
        active: {{ default true .Values.webhook.active }}
        contentType: {{ default "json" .Values.webhook.contentType }}