{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gh-eventsource.fullname" . }}
  namespace: {{ include "gh-eventsource.namespace" . }}
  labels: {{ include "gh-eventsource.labels" . | nindent 4 }}
  annotations: {{ .Values.ingress.annotations | toYaml | nindent 4 }}
spec:
  ingressClassName: {{ default "nginx" .Values.ingress.ingressClassName | quote }}
  rules:
    {{- range .Values.ingress.hosts }}
      - host: {{ . | quote }}
        http:
          paths:
          {{- range $.Values.ingress.paths }}
            - path: {{ .path | quote }}
              pathType: {{ .pathType | quote }}
              backend:
                service:
                  name: {{ include "gh-eventsource.fullname" $ -}}-eventsource-svc
                  port: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
  tls: {{- range .Values.ingress.tls }}
    - secretName: {{ .secretName }}
      hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      
  {{- end }}

{{- end -}}