{{- if .Values.rbac.admin.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-rbac-admin" (include "argo-workflows.fullname" (index $ "Subcharts" "argo-workflows")) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    workflows.argoproj.io/rbac-rule: {{ printf "'%s' in groups" .Values.rbac.admin.rbacRule.matchGroups | quote }}
    workflows.argoproj.io/rbac-rule-precedence: {{ default 0  .Values.rbac.admin.rbacRule.precedence | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-rbac-admin.service-account-token" (include "argo-workflows.fullname" (index $ "Subcharts" "argo-workflows")) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ printf "%s-rbac-admin" (include "argo-workflows.fullname" (index $ "Subcharts" "argo-workflows")) | trunc 63 | trimSuffix "-" }}
type: kubernetes.io/service-account-token
{{- end }}
---
{{- if .Values.rbac.readonly.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-rbac-readonly" (include "argo-workflows.fullname" (index $ "Subcharts" "argo-workflows")) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.rbac.readonly.rbacRule.default }}
    workflows.argoproj.io/rbac-rule: "true"
    {{- else }}
    workflows.argoproj.io/rbac-rule: {{ printf "'%s' in groups" .Values.rbac.readonly.rbacRule.matchGroups | quote }}
    {{- end }}
    workflows.argoproj.io/rbac-rule-precedence: {{ default 0 .Values.rbac.readonly.rbacRule.precedence | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-rbac-readonly.service-account-token" (include "argo-workflows.fullname" (index $ "Subcharts" "argo-workflows")) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ printf "%s-rbac-readonly" (include "argo-workflows.fullname" (index $ "Subcharts" "argo-workflows")) | trunc 63 | trimSuffix "-" }}
type: kubernetes.io/service-account-token
{{- end }}