apiVersion: v2
name: argo-workflows
description: A Helm chart for Argo Workflows.
version: 0.1.0
dependencies:
  - name: argo-workflows
    version: 0.40.1
    repository: https://argoproj.github.io/argo-helm
    condition: argo-workflows.enabled
