{{ if .Values.cert.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "webhook-workflow.fullname" . }}
  namespace: {{ include "webhook-workflow.namespace" . }}
  labels:
    {{- include "webhook-workflow.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.cert.secretName }}
  issuerRef:
    name: {{ .Values.cert.issuerRef.name }}
    kind: {{ .Values.cert.issuerRef.kind }}
  dnsNames: {{ toYaml .Values.cert.dnsNames | nindent 4 }}
{{- end -}}
