apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ include "teamcity.namespace" . }}
spec:
  selector:
    app: {{ .Values.database.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
