apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook
  namespace: sample-webhook
spec:
  secretName: webhook-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - webhook-test.k8s.nabi.kim
