{{ if .Values.agent.pvc.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.agent.pvc.name }}
  namespace: {{ include "teamcity.namespace" . }}
  labels:
    app: {{ template "teamcity.name" . }}
    version: {{ template "teamcity.agent.imageTag" . }}
    chart: {{ template "teamcity.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: {{ default .Values.agent.pvc.storageClass  "default" }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.agent.pvc.storageSize }}
{{ end }}