replicaCount: 1

nameOverride: ""
namespaceOverride: ""

image:
  repository: ""
  pullPolicy: ""
  tag: ""

service:
  type: ClusterIP
  port: 80

tls:
  enabled: true
  secretName: "template-test"
  domains:
  - "template-test.k8s.nabi.kim"

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
  - host: "template-test.k8s.nabi.kim"
    paths:
    - path: /
      pathType: ImplementationSpecific

resources: {}

