apiVersion: v2

name: grafana
description: Grafana Operator for Kubernetes

version: 0.1.0

type: application

dependencies:
  - name: grafana
    version: 7.3.11
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
