grafana:
  enabled: true

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - grafana.k8s.nabi.kim
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.k8s.nabi.kim
