---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: tls-issuer
  namespace: registry
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: account@nabi.kim
    privateKeySecretRef:
      name: tls-key
    solvers:
      - selector: {}
        http01:
          ingress:
            class: traefik
