apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  namespace: image-registry
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/registry
    type: DirectoryOrCreate
