apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  namespace: registry
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/registry
