apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: registry
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 250Gi
  accessModes:
    - ReadWriteOnce
