{{ if .Values.server.enabled }}
{{- if .Values.server.pvc.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "teamcity.server.fullname" . }}-pv
  namespace: {{ template "teamcity.namespace" . }}
spec:
  capacity:
    storage: {{ .Values.server.pvc.storageSize }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "teamcity.fullname" . }}-storageclass
  local:
    path: {{ .Values.server.pvc.path }}
  nodeAffinity: {{ .Values.server.pvc.nodeAffinity | toYaml | nindent 4 }}
{{- end }}
{{ end }}