apiVersion: v1
kind: Service
metadata:
  name: {{ template "teamcity.fullname" . }}
  labels:
    app: {{ template "teamcity.name" . }}
    version: {{ template "teamcity.agent.imageTag" . }}
    chart: {{ template "teamcity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.server.service.annotations }}
  annotations:
    {{ toYaml .Values.server.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: {{ template "teamcity.name" . }}-http
      port: {{ .Values.server.service.port }}
      protocol: TCP
  selector:
    app: {{ template "teamcity.name" . }}
    version: {{ template "teamcity.agent.imageTag" . }}
    chart: {{ template "teamcity.chart" . }}
    release: {{ .Release.Name }}