apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
  namespace: argocd
data:
  applications_api: argocd
  argocd.grpc_web: "true"
  argocd.insecure: "false"
  argocd.plaintext: "false"
  argocd.server_addr: https://argo-cd.k8s.nabi.kim
  registries.conf: |
    registries:
      - name: Nabi Registry
        api_url: https://registry.k8s.nabi.kim
        prefix: registry.k8s.nabi.kim
        ping: yes
        credentials: pullsecret:argocd/dockerhub-secret
        tagsortmode: latest-last
