{{- if .Values.secret.smtp }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.smtp" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secret.smtp }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
