apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: argocd-secret
  issuerRef:
    name: tls-issuer
    kind: ClusterIssuer
  commonName: argo-cd.k8s.nabi.kim
  dnsNames:
  - argo-cd.k8s.nabi.kim
