apiVersion: v2
name: Ghost
description: Ghost Chart for CMS

type: application

version: 1.0.0

dependencies:
  - name: general
    alias: ghost
    version: 1.0.0
    repository: oci://harbor.k8s.nabi.kim/nabi
    condition: ghost.enabled

  - name: general
    alias: mariadb
    version: 1.0.1
    repository: oci://harbor.k8s.nabi.kim/nabi
    condition: mariadb.enabled
