prometheus:
  enabled: true

  server:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/auth-realm: Authentication Required
        nginx.ingress.kubernetes.io/auth-secret: prometheus-auth
        nginx.ingress.kubernetes.io/auth-type: basic
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      hosts:
        - prometheus.k8s.nabi.kim
      tls:
        - secretName: prometheus-tls
          hosts:
            - prometheus.k8s.nabi.kim
