apiVersion: v2
name: argo-cd
description: A Helm chart for ArgoCD in Channel Corp.
type: application
version: 0.1.1
dependencies:
  - name: argo-cd
    version: 5.51.6
    repository: https://argoproj.github.io/argo-helm
    condition: argo-cd.enabled
