{{- if or (or .Values.server.pvc.enabled .Values.agent.pvc.enabled) .Values.database.pvc.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "teamcity.fullname" . }}-storageclass
  namespace: {{ template "teamcity.namespace" . }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- end }}
