{{- if or (or .Values.server.pvc.enabled .Values.agent.pvc.enabled) .Values.database.pvc.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "teamcity.fullname" . }}-storageclass
  namespace: {{ template "teamcity.namespace" . }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- end }}
---
{{- if .Values.server.pvc.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "teamcity.server.fullname" . }}-pv
  namespace: {{ template "teamcity.namespace" . }}
spec:
  capacity:
    storage: {{ .Values.server.pvc.storageSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "teamcity.fullname" . }}-storageclass
  local:
    path: {{ .Values.server.pvc.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - {{ include "teamcity.server.fullname" . }}
{{- end }}
---
{{- if .Values.agent.pvc.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "teamcity.agent.fullname" . }}-pv
  namespace: {{ template "teamcity.namespace" . }}
spec:
  capacity:
    storage: {{ .Values.agent.pvc.storageSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "teamcity.fullname" . }}-storageclass
  local:
    path: {{ .Values.agent.pvc.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - {{ include "teamcity.agent.fullname" . }}
{{- end }}
---
{{- if .Values.database.pvc.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "teamcity.database.fullname" . }}-pv
  namespace: {{ template "teamcity.namespace" . }}
spec:
  capacity:
    storage: {{ .Values.database.pvc.storageSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "teamcity.fullname" . }}-storageclass
  local:
    path: {{ .Values.database.pvc.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - {{ include "teamcity.database.fullname" . }}
{{- end }}