cert-manager:
  enabled: true
  namespace: cert-manager
  installCRDs: true

clusterIssuer:
  enabled: true
  name: "letsencrypt-prod"
  email: "hello@nabi.kim"
  server: "https://acme-v02.api.letsencrypt.org/directory"
