{{ $fullName := include "general.fullname" . }}
{{ $namespace := include "general.namespace" . }}
{{ $labels := include "general.labels" . }}

{{ range .Values.persistentVolumes }}
{{ if .claim.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName}}
  namespace: {{ $namespace }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  storageClassName: {{ $fullName }}
  accessModes: {{- .accessModes | toJson | nindent 4 }}
  resources:
    requests:
      storage: {{ .size }}
{{ end }}
{{ end }}