{{ $fullName := include "general.fullname" . }}
{{ $namespace := include "general.namespace" . }}
{{ $labels := include "general.labels" . }}

{{ range .Values.persistentVolumes }}
{{ if .claim.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default $fullName .name }}
  namespace: {{ $namespace }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  storageClassName: {{ default $fullName .storageClass }}
  accessModes: {{- default .accessModes .claim.accessModes | toJson | nindent 4 }}
  resources:
    requests:
      storage: {{ default .size .claim.size }}
{{ end }}
{{ end }}