{{ if .Values.pvc.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "general.fullname" . }}
  namespace: {{ include "general.namespace" . }}
  labels:
    {{- include "general.labels" . | nindent 4 }}
  annotations: {{- .Values.pvc.annotations | toYaml | nindent 4 }}
spec:
  storageClassName: {{ include "general.fullname" . }}
  accessModes: {{- .Values.pvc.accessModes | toJson | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
{{ end }}