apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: common-database-tls
  namespace: common-database
spec:
  secretName: "common-database-tls"
  issuerRef:
    name: "letsencrypt-prod"
    kind: "ClusterIssuer"
  dnsNames:
    - common-db-read.k8s.nabi.kim
    - common-db-master.k8s.nabi.kim
