argo:
  enabled: true

  nameOverride: argo-cd

  global:
    domain: argo-cd.k8s.nabi.kim

  configs:
    params:
      server.insecure: true

    cm:
      admin.enabled: false
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: 21228a2aabf4a25fcc47
              clientSecret: $dex.github.clientSecret
              orgs:
              - name: nabi-in-k8s
    rbac:
      create: true
      policy.default: "role:readonly"
      policy.csv: |
        g, nabi-in-k8s:Owner, role:admin
      scopes: "[groups, email]"

  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      tls: true
